name: release
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/version.yml"
      - ".github/workflows/Dockerfile.test"
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.v.outputs.rust }}
    steps:
      - name: Rust Version
        id: v
        run: |
          # 最近10个rust版本
          version=$(curl -sL  https://api.github.com/repos/rust-lang/rust/tags | jq -c --raw-output 'map(select(.name | startswith("release") | not)) | sort_by(.name) | reverse | .[:10] | [.[].name]')
          echo "$version"
          echo "rust=$version" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: [version]
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON( needs.version.outputs.rust ) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile.test
          load: true
          push: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            RUST_VERSION=${{ matrix.version }}
  notify:
    runs-on: ubuntu-latest
    needs: [version, test]
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Notify Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run release.yml